// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:animal_aid_app/common/constants/hive_adapter_type_id.dart'
    as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.HiveAdapterTypeIdReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'HiveAdapterTypeId',
            r'.HiveAdapterTypeId',
            7,
            0,
            const prefix0.HiveAdapterTypeIdReflector(),
            const <int>[0],
            const <int>[],
            const <int>[1],
            -1,
            {
              r'hivePostMetaAdapterTypeId': () =>
                  prefix0.HiveAdapterTypeId.hivePostMetaAdapterTypeId
            },
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'hivePostMetaAdapterTypeId', 33941, 0,
            const prefix0.HiveAdapterTypeIdReflector(), -1, -1, -1, null, null),
        r.ImplicitGetterMirrorImpl(
            const prefix0.HiveAdapterTypeIdReflector(), 0, 1)
      ],
      <m.ParameterMirror>[],
      <Type>[prefix0.HiveAdapterTypeId],
      1,
      {},
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
