name: animal_aid_app
description: An aggregator of animal shelters that allows you to view the latest news from them.

publish_to: "none"

version: 0.4.1+35

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ferry: 0.10.5-dev.3
  gql_http_link: 0.4.2
  intl: 0.17.0
  get_it: 7.2.0
  fluro: 2.0.3
  package_info_plus: 4.0.0
  flutter_bloc: 8.0.1
  url_launcher: 6.0.20
  flutter_displaymode: 0.6.0
  built_value: 8.1.4
  liquid_pull_to_refresh: 3.0.1
  lazy_loading_list: 1.0.1
  timeago: 3.2.2
  photo_view: 0.13.0
  animated_size_and_fade: 3.0.0
  built_collection: 5.1.1
  flutter_easyloading: 3.0.5
  liquid_progress_indicator_ns: 1.0.0
  geolocator: 8.2.0
  shared_preferences: 2.0.13
  modal_bottom_sheet: 2.0.1
  flutter_native_splash: 2.1.5
  provider: 6.0.0
  flutter_parsed_text: 2.2.1
  flutter_svg: 1.0.3
  auto_size_text: 3.0.0
  equatable: 2.0.3
  hive: 2.2.1
  hive_flutter: 1.1.0
  reflectable: 3.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: 1.0.4
  ferry_generator: 0.5.0-dev.10
  build_runner: 2.1.8
  built_value_generator: 8.3.0
  flutter_launcher_icons: 0.11.0
  storybook_flutter: 0.10.1
  recase: 4.0.0
  mockito: 5.1.0
  intl_utils: 2.6.1
  dart_code_metrics: 4.15.2
  hive_generator: 1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_with_text.png
    - assets/images/flat_map.png
    - assets/images/onboarding/onboarding_1.svg
    - assets/images/onboarding/onboarding_2.svg
    - assets/images/onboarding/onboarding_3.svg
    - assets/images/onboarding/onboarding_placeholder.svg
    - assets/cfg/

flutter_icons:
  android: "launcher_icon"
  ios: false
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon-square.png"

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
